#!/usr/bin/env python3
"""Codegen: turn the 19 renderer.json specs into Sources/RendererGeometry/GeneratedRenderers.swift.
Run from the repo root:  python3 renderers/codegen_swift.py
- dome kernel output index = sphere speaker id - 1 (0..29); LFE channels carry no dome gain.
- the sub (output 30) is fed by bass management (mono bass downmix), described in subBass.
"""
import json, os, glob

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPECS=os.path.join(ROOT,"renderers")
OUT=os.path.join(ROOT,"Sources","RendererGeometry","GeneratedRenderers.swift")
ORDER=["mono_1_0","stereo_2_0","binaural_2_0_narrow","quad_4_0","5_1","5_1_2","5_1_4",
 "7_1","7_1_2","7_1_4","9_1_4","9_1_6","auro_8_0","auro_9_1","auro_10_1",
 "auro_11_1_7_1_4h","auro_11_1_5_1_5h_t","auro_13_1","harmony_bloom_8ch"]

def d(v): return repr(float(v))
def s(v): return '"'+str(v).replace('\\','\\\\').replace('"','\\"')+'"'

sphere=json.load(open(os.path.join(SPECS,"sphere-fey-30.1.json")))["speakers"]
def emit_sphere():
    rows=", ".join(f"(x: {d(p['x'])}, y: {d(p['y'])}, z: {d(p['z'])})" for p in sphere)
    return f"    public static let sphereSpeakers: [(x: Double, y: Double, z: Double)] = [\n        {rows}\n    ]\n"

def emit_renderer(spec):
    chans=[]
    for c in spec["channels"]:
        chans.append(f'GeneratedChannel(index: {c["index"]}, label: {s(c["label"])}, '
                     f'role: {s(c["role"])}, azimuthDeg: {d(c["azimuthDeg"])}, '
                     f'elevationDeg: {d(c["elevationDeg"])}, isLFE: {str(c["lfe"]).lower()})')
    # dome kernel: per input channel, entries to dome speakers (0..29). LFE -> [].
    kcols=[]
    for col in spec["kernel"]["columns"]:
        if col.get("lfe"):
            kcols.append("[]"); continue
        entries=", ".join(f"GeneratedKernelEntry(output: {g[0]-1}, gain: {d(g[1])})"
                          for g in col["gains"] if 1<=g[0]<=30)
        kcols.append(f"[{entries}]")
    bm=spec["bassManagement"]; sf=bm["subFeed"]
    fr=", ".join(str(c["channelIndex"]) for c in sf["fullRangeBassDownmix"])
    lf=", ".join(str(c["channelIndex"]) for c in sf["lfe"])
    sub=(f'GeneratedSubBass(derivedLFE: {str(bm["derivedLFE"]).lower()}, monoBass: true, '
         f'lowPassHz: {d(bm["subFeedLowPass"]["freqHz"])}, slopeDbPerOct: {d(bm["subFeedLowPass"]["slopeDbPerOct"])}, '
         f'lfeGainDb: {d(bm["lfeGainDb"])}, fullRangeInputs: [{fr}], lfeInputs: [{lf}])')
    parametric=str(bool(spec.get("parametric"))).lower()
    chans_s="[\n            "+",\n            ".join(chans)+"\n        ]"
    kern_s="[\n            "+",\n            ".join(kcols)+"\n        ]"
    return (f'    GeneratedRenderer(\n'
            f'        layout: {s(spec["layout"])}, displayName: {s(spec["displayName"])}, '
            f'family: {s(spec["family"])}, channelCount: {spec["channelCount"]}, isParametric: {parametric},\n'
            f'        channels: {chans_s},\n'
            f'        domeKernel: {kern_s},\n'
            f'        subBass: {sub}\n'
            f'    )')

specs={}
for f in glob.glob(os.path.join(SPECS,"*","*.renderer.json")):
    j=json.load(open(f)); specs[j["layout"]]=j
renderers=",\n".join(emit_renderer(specs[l]) for l in ORDER if l in specs)

hdr='''// GENERATED by renderers/codegen_swift.py — DO NOT EDIT BY HAND.
// Source: renderers/<layout>/<layout>.renderer.json (geometry-engine specs).
// Output index 0..29 = dome speaker (id = index + 1); output 30 = sub (fed by bass management).
import Foundation

public struct GeneratedKernelEntry: Sendable, Hashable {
    public let output: Int
    public let gain: Double
    public init(output: Int, gain: Double) { self.output = output; self.gain = gain }
}

public struct GeneratedChannel: Sendable, Hashable {
    public let index: Int
    public let label: String
    public let role: String
    public let azimuthDeg: Double
    public let elevationDeg: Double
    public let isLFE: Bool
    public init(index: Int, label: String, role: String, azimuthDeg: Double, elevationDeg: Double, isLFE: Bool) {
        self.index = index; self.label = label; self.role = role
        self.azimuthDeg = azimuthDeg; self.elevationDeg = elevationDeg; self.isLFE = isLFE
    }
}

public struct GeneratedSubBass: Sendable, Hashable {
    public let derivedLFE: Bool
    public let monoBass: Bool
    public let lowPassHz: Double
    public let slopeDbPerOct: Double
    public let lfeGainDb: Double
    public let fullRangeInputs: [Int]
    public let lfeInputs: [Int]
    public init(derivedLFE: Bool, monoBass: Bool, lowPassHz: Double, slopeDbPerOct: Double, lfeGainDb: Double, fullRangeInputs: [Int], lfeInputs: [Int]) {
        self.derivedLFE = derivedLFE; self.monoBass = monoBass; self.lowPassHz = lowPassHz
        self.slopeDbPerOct = slopeDbPerOct; self.lfeGainDb = lfeGainDb
        self.fullRangeInputs = fullRangeInputs; self.lfeInputs = lfeInputs
    }
}

public struct GeneratedRenderer: Sendable, Hashable {
    public let layout: String
    public let displayName: String
    public let family: String
    public let channelCount: Int
    public let isParametric: Bool
    public let channels: [GeneratedChannel]
    public let domeKernel: [[GeneratedKernelEntry]]
    public let subBass: GeneratedSubBass
    public init(layout: String, displayName: String, family: String, channelCount: Int, isParametric: Bool, channels: [GeneratedChannel], domeKernel: [[GeneratedKernelEntry]], subBass: GeneratedSubBass) {
        self.layout = layout; self.displayName = displayName; self.family = family
        self.channelCount = channelCount; self.isParametric = isParametric
        self.channels = channels; self.domeKernel = domeKernel; self.subBass = subBass
    }
}

public enum GeneratedRenderers {
    public static let domeSpeakerCount = 30
    public static let subOutputIndex = 30
    public static let totalOutputs = 31

'''
body=(hdr+emit_sphere()+
 "\n    public static let all: [GeneratedRenderer] = [\n"+renderers+"\n    ]\n\n"
 "    public static func byLayout(_ id: String) -> GeneratedRenderer? { all.first { $0.layout == id } }\n"
 "    public static func byChannelCount(_ n: Int) -> [GeneratedRenderer] { all.filter { $0.channelCount == n } }\n"
 "}\n")
os.makedirs(os.path.dirname(OUT),exist_ok=True)
open(OUT,"w").write(body)
print(f"wrote {OUT} ({len(body.splitlines())} lines, {len([l for l in ORDER if l in specs])} renderers)")
